Upgrade gql java 9 - *do not merge yet*
Enigmatis/graphql-java-annotations pull request #176
Opened 2018-06-18 10:47 UTC by yarinvak

Upgrading to graphql - java 9
+
Adding directives support

The PR is not fully ready yet but I've opened it so you can have your remarks
I still have to add tests and readme

2018-06-20 12:13 UTC, guy120494 requested changes

2018-06-20 12:13 UTC, guy120494 commented on src/test/java/graphql/annotations/processor/retrievers/fieldBuilders/DirectivesBuilderTest.java
> +    public void testDecoratedFieldWithArguments_argumentsValuesLongerThanArgumentsNumber_exceptionIsThrown() throws Exception {
https://stackoverflow.com/questions/2469911/how-do-i-assert-my-exception-message-with-junit-test-annotation
This is the way to test that exception is thrown

2018-06-20 12:13 UTC, guy120494 commented on src/test/java/graphql/annotations/processor/retrievers/fieldBuilders/DirectivesBuilderTest.java
> +    public void testDecoratedFieldWithArguments_directiveArgumentIsNotAScalarType_exceptionIsThrown() throws Exception {
Be consistent with the names. "exceptionIsThrown" or "throwAnException"

2018-06-20 12:13 UTC, guy120494 commented on src/test/java/graphql/annotations/directives/DirectiveWiringMapRetrieverTest.java
> +    public void getDirectiveWiringMap_wiringClassIsPrivate_throwAnException() throws Exception {
Which exception is thrown? specify it in the test's name

2018-06-20 12:13 UTC, guy120494 commented on src/test/java/graphql/annotations/directives/DirectiveWirerTest.java
> +    public void wireGraphQLInputObjectField_invalidLocations_exception() throws Exception {
Be consistent with names of tests that throw exception

2018-06-20 12:13 UTC, guy120494 commented on src/main/java/graphql/annotations/processor/retrievers/fieldBuilders/DirectivesBuilder.java
> +    private GraphQLDirective transformArgs(GraphQLDirective graphQLDirective, String[] argumentValues) {
Split this method

2018-06-20 12:13 UTC, guy120494 commented on src/main/java/graphql/annotations/directives/DirectiveWirer.java
> +
Delete blank line

2018-06-20 12:13 UTC, guy120494 commented on src/main/java/graphql/annotations/directives/DirectiveWirer.java
> +            if (element instanceof GraphQLFieldDefinition) {
Change to Map<Class, Function> which the key is "GraphQLFieldDefinition,.class" and so on, and the value is the function inside the if statement

2018-07-05 10:19 UTC, osher-sade commented on src/main/java/graphql/annotations/directives/Directive.java
> +    //    Class<? extends BasicDirectiveInfo> info();
Remove redundant comment

2018-08-05 11:09 UTC, merged