Fix deprecated annotation
Enigmatis/graphql-java-annotations pull request #255
Opened 2020-08-11 06:32 UTC by itaykl

2020-08-11 06:46 UTC, DoctorVoid requested changes

2020-08-11 06:46 UTC, DoctorVoid commented on build.gradle
> +//apply plugin: 'osgi'
comment

2020-08-11 06:46 UTC, DoctorVoid commented on src/test/java/graphql/annotations/processor/retrievers/fieldBuilders/DeprecateBuilderTest.java
> +
Add test for deprecated on type

2020-08-11 06:46 UTC, DoctorVoid commented on src/test/java/graphql/annotations/processor/retrievers/fieldBuilders/DeprecateBuilderTest.java
> +    @GraphQLDeprecate("test field deprecated")
make codecov happy by lifting those fields to the top of the file above the resolver functions

2020-08-11 06:51 UTC, osher-sade commented
Check if the main README needs to be updated

2020-08-12 09:30 UTC, yarinvak commented on src/test/java/graphql/annotations/processor/retrievers/fieldBuilders/DeprecateBuilderTest.java
> +    public void build_deprecatedAnnotationExistsOnField_returnNull() throws NoSuchFieldException {
does not exist

2020-08-12 09:41 UTC, yarinvak approved these changes

2020-08-12 09:42 UTC, merged