Adopt is dead, long live Zulu!
Enigmatis/graphql-java-annotations pull request #279
Opened 2021-08-28 20:43 UTC by geertjanw

2021-09-06 14:37 UTC, yarinvak commented
would appreciate elaboration on your change

2021-09-06 15:03 UTC, geertjanw commented
Adopt no longer exists. Two options for v2 right now are 'temurin' or 'zulu'. The first one, 'temurin' is new, and doesn't have all the releases, e.g., the Temurin history starts from 8.0.302, 11.0.12, and 16.0.2, while Zulu supports all versions of these releases.

2021-09-06 15:05 UTC, geertjanw commented
Right now you're testing only on '8', which is not a fixed version, but that is whatever the latest version of '8' is. You're recommended as a best practise to set the latest version of a release, as well as a fixed version, so that when your build breaks and the fixed version is green while the latest version is red, you'll know that the broken build is because of the latest version of the JDK and not because of anything in your own code.

Here's an example:

https://github.com/HdrHistogram/HdrHistogram/blob/master/.github/workflows/maven.yml

2023-05-05 09:44 UTC, Fgerthoffert requested changes
We're helping on project maintenance.

Once the change is done we will merge your PR. Without answer within 2 months, we will close this PR and create a separate one for the update to zulu.

2023-05-05 09:44 UTC, Fgerthoffert commented on .github/workflows/build.yml
> +          distribution: 'zulu'
Could you also update to zulu in the publish workflow ?

2023-05-26 08:27 UTC, merged